name: Docs
on:
  push:
    branches:
      - master
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}@${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-minify-plugin
      - name: Build
        run: mkdocs build --strict
      - name: Deploy
        run: mkdocs gh-deploy --force
